Dev
ruperson/Android_ImageSeeker pull request #3
Opened 2018-11-29 11:19 UTC by ruperson

gogogo

2018-12-25 11:33 UTC, aleksej-lapenok requested changes

2018-12-25 11:33 UTC, lapenok-aleksej commented on ImageSeeker/.idea/codeStyles/Project.xml
> +<component name="ProjectCodeStyleConfiguration">
файлы идеи тут не нужны

2018-12-25 11:33 UTC, lapenok-aleksej commented on ImageSeeker/app/src/main/java/ru/ifmo/ctddev/vanyan/imageseeker/ChildActivity.java
> +            exit(1);
exit??? wtf???

2018-12-25 11:33 UTC, lapenok-aleksej commented on ImageSeeker/app/src/main/java/ru/ifmo/ctddev/vanyan/imageseeker/MainActivity.java
> +        return new AsyncTaskLoader<String>(this) { // this won't leak
а выглядит, как будто утечет

2018-12-25 11:33 UTC, lapenok-aleksej commented on ImageSeeker/app/src/main/java/ru/ifmo/ctddev/vanyan/imageseeker/utilities/NetworkUtils.java
> +        OkHttpClient client = new OkHttpClient();
зачем создавать клиента каждый раз?

2018-12-25 13:05 UTC, ruperson commented on ImageSeeker/app/src/main/java/ru/ifmo/ctddev/vanyan/imageseeker/ChildActivity.java
> +            exit(1);
> exit??? wtf???
Валера сказал, что при получении невозможных условий нужно "смачно падать"
Кажется я смачно падаю

2018-12-25 13:13 UTC, lapenok-aleksej commented on ImageSeeker/app/src/main/java/ru/ifmo/ctddev/vanyan/imageseeker/ChildActivity.java
> +            exit(1);
Смачно падать - бросить исключение
и тогда перед этим писать в логи не на уровне дебага, а на уровне error или wtf

2019-01-12 21:22 UTC, aleksej-lapenok approved these changes

2019-01-14 14:36 UTC, nikitakaberov approved these changes

2019-01-21 20:23 UTC, merged